language: python
python:
  - "2.7"
  - "2.7_with_system_site_packages"
  # - "3.2" # no rpy2 or biopython support for Python3
  - "3.3"
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-rpy2 python-lxml python-biopython python-xlwt python-scikits-learn  python-cluster
 # - sudo apt-get install -qq python3-scipy python3-numpy python3-setuptools
 # - sudo easy_install3 pip
 # - sudo pip3.3 install biopython
 # - sudo pip3.3 install rpy2

# - git clone https://github.com/pymzml/pymzML.git
# - "cd pymzML && python setup.py install && cd .."
install:
  - pip install rpy2 # for Python 3.3
  - travis_retry python setup.py develop
script: "nosetests -w test/"
cache: pip
