language: python
python:
  - "2.7"
  - "2.7_with_system_site_packages"
  # - "3.2" # no rpy2 or biopython support for Python3
  - "3.3"
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-rpy2 python-lxml 
 - sudo apt-get install -qq python-biopython python-xlwt python-scikits-learn 
 - sudo apt-get install -qq python-cluster
# - git clone https://github.com/pymzml/pymzML.git
# - "cd pymzML && python setup.py install && cd .."
 - git clone https://github.com/hroest/scikit-datasmooth.git
 - "cd scikit-datasmooth && python setup.py install && cd .."
install:
  # for Python 2.7 and 3.3 w/o system packages, install rpy2 manually
  #  note rpy2 > 2.5.6 (certainly > 2.6.1) will NOT work with R 2.x any more!
  #  we use 2.2.5 (same as Ubuntu precise 12.04)
  - pip install rpy2==2.2.5
  - travis_retry python setup.py develop
script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then nosetests -w test/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then nosetests -w test/; fi
cache: pip
